name: Test suite

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        python ./scripts/bz.py
        chmod +x ./bin/neutralino-win_x64.exe
      shell: cmd
      
    - name: Setup Spec Requirements
      working-directory: ./bin/extensions/sampleextension 
      run: npm ci
      
    - name: Run Spec
      working-directory: ./spec 
      run: | 
        npm ci
        npm run test
