name: Test suite

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [arm64]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Build
      if: ${{ matrix.arch == 'arm64' || matrix.arch == 'armhf' }}
      uses: uraimo/run-on-arch-action@v2
      id: build-package
      with:
        arch: ${{ matrix.arch == 'arm64' && 'aarch64' || 'armv7' }}
        distro: ubuntu20.04
        install: |
          sudo apt-get update
          sudo apt-get install -y -f \
          libgtk-3-dev \
          libwebkit2gtk-4.0-37 \
          libwebkit2gtk-4.0-dev \
          libayatana-appindicator3-1 \
          xvfb \
          git \
          python3 \
          g++ \
          pkg-config

        githubToken: ${{ github.token }}

        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          ./scripts/bz.py

    - name: Setup Spec Requirements
      working-directory: ./bin/extensions/sampleextension
      run: npm ci

    - name: Run Spec
      working-directory: ./spec
      run: |
        sudo cp ./ld-linux-aarch64.so.1 /lib/
        npm ci
        xvfb-run npm run test
